//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankFileMster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BankFileMster()
        {
            this.BankFileDeteil = new HashSet<BankFileDeteil>();
        }
    
        public decimal Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int IdShip { get; set; }
        public Nullable<long> IdPersonnel { get; set; }
        public Nullable<long> TotalCost { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankFileDeteil> BankFileDeteil { get; set; }
    }
}
