//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankFileDeteil
    {
        public decimal Id { get; set; }
        public decimal IdBankFile { get; set; }
        public Nullable<long> IdPersonnel { get; set; }
        public Nullable<long> TotalCost { get; set; }
    
        public virtual BankFileMster BankFileMster { get; set; }
    }
}
