//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class BimehDeteil
    {
        public decimal Id { get; set; }
        public decimal IdBimehMaster { get; set; }
        public string DSW_ID { get; set; }
        public Nullable<decimal> DSW_YY { get; set; }
        public Nullable<decimal> DSW_MM { get; set; }
        public string DSW_LISTNO { get; set; }
        public string DSW_ID1 { get; set; }
        public string DSW_FNAME { get; set; }
        public string DSW_LNAME { get; set; }
        public string DSW_DNAME { get; set; }
        public string DSW_IDNO { get; set; }
        public string DSW_IDPLC { get; set; }
        public string DSW_IDATE { get; set; }
        public string DSW_BDATE { get; set; }
        public string DSW_SEX { get; set; }
        public string DSW_NAT { get; set; }
        public string DSW_OCP { get; set; }
        public string DSW_SDATE { get; set; }
        public string DSW_EDATE { get; set; }
        public Nullable<decimal> DSW_DD { get; set; }
        public Nullable<decimal> DSW_ROOZ { get; set; }
        public Nullable<decimal> DSW_MAH { get; set; }
        public Nullable<decimal> DSW_MAZ { get; set; }
        public Nullable<decimal> DSW_MASH { get; set; }
        public Nullable<decimal> DSW_TOTL { get; set; }
        public Nullable<decimal> DSW_BIME { get; set; }
        public Nullable<decimal> DSW_PRATE { get; set; }
        public string DSW_JOB { get; set; }
        public string PER_NATCOD { get; set; }
    
        public virtual BimehMaster BimehMaster { get; set; }
    }
}
