//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebtHistory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DebtHistory()
        {
            this.SafarToHandMoney = new HashSet<SafarToHandMoney>();
        }
    
        public long Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int IdShip { get; set; }
        public long IdPersonnel { get; set; }
        public string Description { get; set; }
        public long Price { get; set; }
        public Nullable<decimal> IdNote { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Note Note { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual Ship Ship { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SafarToHandMoney> SafarToHandMoney { get; set; }
    }
}
