//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kala
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kala()
        {
            this.SafarToHandMoney = new HashSet<SafarToHandMoney>();
            this.SafarToFactor = new HashSet<SafarToFactor>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public long IdTypeKala { get; set; }
        public int IdUnit { get; set; }
        public long IdPersonnel { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsActive { get; set; }
        public Nullable<int> Sort { get; set; }
    
        public virtual Personnel Personnel { get; set; }
        public virtual OptionParameter OptionParameter { get; set; }
        public virtual Unit Unit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SafarToHandMoney> SafarToHandMoney { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SafarToFactor> SafarToFactor { get; set; }
    }
}
