//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Note
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Note()
        {
            this.DebtHistory = new HashSet<DebtHistory>();
        }
    
        public decimal Id { get; set; }
        public long IdPersonnel { get; set; }
        public int IdShip { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Description { get; set; }
        public long Price { get; set; }
        public Nullable<long> IdSafar { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebtHistory> DebtHistory { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual Ship Ship { get; set; }
        public virtual Safar Safar { get; set; }
    }
}
