//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.PackageToShip = new HashSet<PackageToShip>();
        }
    
        public decimal Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public long IdPersonnel { get; set; }
        public long Price { get; set; }
        public int IdPackage { get; set; }
        public int IdShip { get; set; }
        public decimal IdShomareOrder { get; set; }
        public string Ref { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Package Package { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual Ship Ship { get; set; }
        public virtual ShomareOrder ShomareOrder { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PackageToShip> PackageToShip { get; set; }
    }
}
