//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class PackageToShip
    {
        public long Id { get; set; }
        public Nullable<int> IdPackage { get; set; }
        public int IdShip { get; set; }
        public long TotalPrice { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsPay { get; set; }
        public long IdPersonnel { get; set; }
        public System.DateTime ExpireDate { get; set; }
        public Nullable<decimal> IdOrder { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual Package Package { get; set; }
        public virtual Ship Ship { get; set; }
    }
}
