//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolePernonnel
    {
        public int Id { get; set; }
        public int IdRole { get; set; }
        public long IdPersonnel { get; set; }
    
        public virtual Personnel Personnel { get; set; }
        public virtual Role Role { get; set; }
    }
}
