//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SafarToAfrad
    {
        public long Id { get; set; }
        public long IdSafar { get; set; }
        public long IdPernonnel { get; set; }
        public int IdSemat { get; set; }
        public decimal Ratio { get; set; }
        public Nullable<long> TotalPrice { get; set; }
        public bool IsBimeh { get; set; }
        public int PriceBimeh { get; set; }
        public Nullable<long> Nakhales { get; set; }
        public Nullable<long> KasriTabakhi { get; set; }
    
        public virtual Personnel Personnel { get; set; }
        public virtual Safar Safar { get; set; }
        public virtual Semat Semat { get; set; }
    }
}
