//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SafarToSahamDar
    {
        public long Id { get; set; }
        public long IdSafar { get; set; }
        public long IdPersonnel { get; set; }
        public int Rate { get; set; }
        public long TotalPrice { get; set; }
    
        public virtual Personnel Personnel { get; set; }
        public virtual Safar Safar { get; set; }
    }
}
