//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SafarToHandMoney
    {
        public long Id { get; set; }
        public long IdSafar { get; set; }
        public long IdPersonnel { get; set; }
        public Nullable<int> IdKala { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<long> Price { get; set; }
        public System.DateTime CreateDateMoney { get; set; }
        public string Tozihat { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<long> TotalPrice { get; set; }
        public Nullable<int> IdUnit { get; set; }
        public bool IsPay { get; set; }
        public Nullable<long> IdDebtHistory { get; set; }
    
        public virtual DebtHistory DebtHistory { get; set; }
        public virtual Kala Kala { get; set; }
        public virtual Personnel Personnel { get; set; }
        public virtual Safar Safar { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
