//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class SafarToFactor
    {
        public long Id { get; set; }
        public long IdSafar { get; set; }
        public int IdKala { get; set; }
        public long IdTypeFactor { get; set; }
        public Nullable<decimal> Tedad { get; set; }
        public long Price { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ShomareFactor { get; set; }
        public Nullable<System.DateTime> DateFactor { get; set; }
        public string TaminKhonanade { get; set; }
        public string Moshtari { get; set; }
        public string Tozihat { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public long TotalPrice { get; set; }
        public Nullable<int> IdUnit { get; set; }
        public Nullable<long> IdTankhaGardan { get; set; }
    
        public virtual Kala Kala { get; set; }
        public virtual OptionParameter OptionParameter { get; set; }
        public virtual Safar Safar { get; set; }
        public virtual TankhaGardan TankhaGardan { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
