//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Safar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Safar()
        {
            this.SafarToAfrad = new HashSet<SafarToAfrad>();
            this.SafarToHandMoney = new HashSet<SafarToHandMoney>();
            this.SafarToFactor = new HashSet<SafarToFactor>();
            this.SafarToSahamDar = new HashSet<SafarToSahamDar>();
            this.Note = new HashSet<Note>();
        }
    
        public long Id { get; set; }
        public long IdPersonnel { get; set; }
        public long IdSoom { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public decimal PriceKharid { get; set; }
        public decimal PriceMahtaiaj { get; set; }
        public decimal PriceForosh { get; set; }
        public decimal PriceTamirat { get; set; }
        public long FactorMosaede { get; set; }
        public string Tozihat { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsActive { get; set; }
        public string Title { get; set; }
        public int PriceFood { get; set; }
        public decimal TamiratGolate { get; set; }
        public long GolateBase { get; set; }
        public decimal GolateTedadKol { get; set; }
        public int SafarCount { get; set; }
        public long JamKolSoodAzSafar { get; set; }
        public Nullable<long> DaramadSafarFrosh_Machele { get; set; }
        public bool IsCheckout { get; set; }
        public Nullable<bool> IsOne { get; set; }
    
        public virtual Personnel Personnel { get; set; }
        public virtual Soom Soom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SafarToAfrad> SafarToAfrad { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SafarToHandMoney> SafarToHandMoney { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SafarToFactor> SafarToFactor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SafarToSahamDar> SafarToSahamDar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Note { get; set; }
    }
}
