//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShipToPay
    {
        public long Id { get; set; }
        public int IdShip { get; set; }
        public int IdPackage { get; set; }
        public int Price { get; set; }
        public Nullable<decimal> IdShomareOrder { get; set; }
        public bool IsPay { get; set; }
        public string BankReferenceKey { get; set; }
        public string BankReceiptNumber { get; set; }
        public Nullable<System.DateTime> ExpiryDatePackage { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Package Package { get; set; }
        public virtual Ship Ship { get; set; }
        public virtual ShomareOrder ShomareOrder { get; set; }
    }
}
