//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class Soom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Soom()
        {
            this.Safar = new HashSet<Safar>();
        }
    
        public long Id { get; set; }
        public long IdPersonnel { get; set; }
        public int IdShip { get; set; }
        public bool IsActive { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string Tozihat { get; set; }
        public int SommConter { get; set; }
        public int SafarCounter { get; set; }
        public string TiTle { get; set; }
        public bool IsCheckout { get; set; }
    
        public virtual Personnel Personnel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Safar> Safar { get; set; }
        public virtual Ship Ship { get; set; }
    }
}
