//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TankhaGardan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TankhaGardan()
        {
            this.SafarToFactor = new HashSet<SafarToFactor>();
            this.TankhaGardanToShip = new HashSet<TankhaGardanToShip>();
        }
    
        public long Id { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public long IdUser { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string FullName { get; set; }
    
        public virtual Personnel Personnel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SafarToFactor> SafarToFactor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TankhaGardanToShip> TankhaGardanToShip { get; set; }
    }
}
