//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ship.Model.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TankhaGardanToShip
    {
        public long Id { get; set; }
        public long IdTankhaGardan { get; set; }
        public int IdShip { get; set; }
    
        public virtual Ship Ship { get; set; }
        public virtual TankhaGardan TankhaGardan { get; set; }
    }
}
